package dev.deepjava.jdbc;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLTransientConnectionException;
import java.sql.Statement;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;
import java.util.concurrent.atomic.AtomicReference;

public final class JdbcPoolLab {
    private JdbcPoolLab() { }

    public static void main(String[] args) throws Exception {
        HikariConfig config = new HikariConfig();
        config.setPoolName("deep-java-pool");
        config.setJdbcUrl("jdbc:h2:mem:pool;DB_CLOSE_DELAY=-1");
        config.setUsername("sa");
        config.setMaximumPoolSize(2);
        config.setMinimumIdle(0);
        config.setConnectionTimeout(250);
        config.setInitializationFailTimeout(1_000);

        try (HikariDataSource dataSource = new HikariDataSource(config)) {
            initializeAndBatch(dataSource);
            verifyPoolAdmission(dataSource);
            try (Connection connection = dataSource.getConnection();
                 PreparedStatement query = connection.prepareStatement(
                         "select name from item order by id", ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY)) {
                query.setFetchSize(2);
                try (ResultSet rows = query.executeQuery()) {
                    java.util.ArrayList<String> names = new java.util.ArrayList<>();
                    while (rows.next()) names.add(rows.getString(1));
                    assert names.equals(List.of("alpha", "x'); drop table item; --", "omega")) : names;
                }
            }
            System.out.println("JDBC binding, batch, cursor iteration and pool timeout verified");
        }
    }

    private static void initializeAndBatch(HikariDataSource dataSource) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement ddl = connection.createStatement()) {
            ddl.execute("create table item(id bigint generated by default as identity, name varchar(128))");
        }
        try (Connection connection = dataSource.getConnection();
             PreparedStatement insert = connection.prepareStatement("insert into item(name) values (?)")) {
            connection.setAutoCommit(false);
            for (String value : List.of("alpha", "x'); drop table item; --", "omega")) {
                insert.setString(1, value);
                insert.addBatch();
            }
            int[] counts = insert.executeBatch();
            assert counts.length == 3;
            connection.commit();
        }
    }

    private static void verifyPoolAdmission(HikariDataSource dataSource) throws Exception {
        try (Connection first = dataSource.getConnection(); Connection second = dataSource.getConnection()) {
            AtomicReference<SQLException> failure = new AtomicReference<>();
            AtomicLong elapsedMillis = new AtomicLong();
            Thread waiter = Thread.startVirtualThread(() -> {
                long started = System.nanoTime();
                try (Connection ignored = dataSource.getConnection()) {
                    throw new AssertionError("third concurrent borrower should time out");
                } catch (SQLException expected) {
                    elapsedMillis.set((System.nanoTime() - started) / 1_000_000);
                    failure.set(expected);
                }
            });
            waiter.join(2_000);
            assert !waiter.isAlive();
            assert failure.get() instanceof SQLTransientConnectionException : failure.get();
            assert elapsedMillis.get() >= 200 : elapsedMillis;
            assert dataSource.getHikariPoolMXBean().getActiveConnections() == 2;
            System.out.println("pool timeout elapsedMillis=" + elapsedMillis.get());
        }
    }
}
