apiVersion: apps/v1
kind: Deployment
metadata:
  name: invalid-field-demo
  namespace: dk-course
spec:
  replicaz: 1
  selector:
    matchLabels:
      app: invalid
  template:
    metadata:
      labels:
        app: invalid
    spec:
      containers:
        - name: web
          image: nginx:1.29-alpine
