apiVersion: v1
kind: Pod
metadata:
  name: defaulted-resources
  namespace: lab-dev
  labels:
    app.kubernetes.io/name: defaulted-resources
    environment: development
    tier: backend
spec:
  restartPolicy: Never
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: server
      image: dk-course/pod-lifecycle:13
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
