package dev.deepjava.spring;

import java.util.concurrent.atomic.AtomicInteger;
import javax.sql.DataSource;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

public final class TransactionBoundaryLab {
    static final class CountingTransactionManager extends DataSourceTransactionManager {
        final AtomicInteger begins = new AtomicInteger();
        CountingTransactionManager(DataSource dataSource) { super(dataSource); }
        @Override protected void doBegin(Object transaction, TransactionDefinition definition) {
            begins.incrementAndGet();
            super.doBegin(transaction, definition);
        }
    }

    public static class AuditService {
        private final JdbcTemplate jdbc;
        AuditService(JdbcTemplate jdbc) { this.jdbc = jdbc; }
        @Transactional(propagation = Propagation.REQUIRES_NEW)
        public void record(String value) { jdbc.update("insert into audit(message) values (?)", value); }
    }

    public static class OrderService {
        private final JdbcTemplate jdbc;
        private final AuditService audit;
        OrderService(JdbcTemplate jdbc, AuditService audit) { this.jdbc = jdbc; this.audit = audit; }

        @Transactional
        public void selfInvocation() {
            jdbc.update("insert into orders(name) values ('self')");
            innerRequiresNew(); // this call does not cross the proxy
        }

        @Transactional(propagation = Propagation.REQUIRES_NEW)
        public void innerRequiresNew() { jdbc.update("insert into audit(message) values ('self-inner')"); }

        @Transactional
        public void externalInvocation() {
            jdbc.update("insert into orders(name) values ('external')");
            audit.record("external-inner"); // crosses a second proxy and suspends the outer transaction
        }
    }

    @Configuration(proxyBeanMethods = false)
    @EnableTransactionManagement(proxyTargetClass = true)
    static class Config {
        @Bean DataSource dataSource() {
            return new DriverManagerDataSource("jdbc:h2:mem:txlab;DB_CLOSE_DELAY=-1", "sa", "");
        }
        @Bean JdbcTemplate jdbcTemplate(DataSource dataSource) { return new JdbcTemplate(dataSource); }
        @Bean CountingTransactionManager transactionManager(DataSource dataSource) {
            return new CountingTransactionManager(dataSource);
        }
        @Bean AuditService auditService(JdbcTemplate jdbc) { return new AuditService(jdbc); }
        @Bean OrderService orderService(JdbcTemplate jdbc, AuditService audit) { return new OrderService(jdbc, audit); }
    }

    private TransactionBoundaryLab() { }

    public static void main(String[] args) {
        try (AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(Config.class)) {
            JdbcTemplate jdbc = context.getBean(JdbcTemplate.class);
            jdbc.execute("create table orders(id bigint generated by default as identity, name varchar(64))");
            jdbc.execute("create table audit(id bigint generated by default as identity, message varchar(64))");
            OrderService service = context.getBean(OrderService.class);
            CountingTransactionManager transactions = context.getBean(CountingTransactionManager.class);

            service.selfInvocation();
            assert transactions.begins.get() == 1 : transactions.begins;
            service.externalInvocation();
            assert transactions.begins.get() == 3 : transactions.begins;
            assert jdbc.queryForObject("select count(*) from orders", Integer.class) == 2;
            assert jdbc.queryForObject("select count(*) from audit", Integer.class) == 2;
            System.out.println("transaction proxy boundary verified, physicalBegins=" + transactions.begins);
        }
    }
}
